### ISSUE TITLE
Heroku crashes after starting

### ISSUE THREAD

**Issue by BrandonS8** [oscarmorrison/nightmare-heroku#12]
As soon as I start the app it crashes with this error: 
2019-02-21T04:11:48.050563+00:00 heroku[web.1]: Process exited with status 139

I've done nothing but clone the repo and follow the instructions.

**Comment by leviwheatcroft** [comment]
The heroku logs will give you a lot more detail about what's gone wrong.

**Comment by BrandonS8** [comment]
The error I listed is all the logs have.

**Comment by jrhodes621** [comment]
I experienced the same issue; I solved this by specifying a node version, version 8.11.4 worked for me
