### ISSUE TITLE
Cedar-14 is EOL

### ISSUE THREAD

**Issue by yashaRO** [oscarmorrison/nightmare-heroku#13]
Is there an alternative to Cedar-14?

**Comment by ghost** [comment]
@yashaRO Ever find an alternative configuration? My tech stack relies on nightmare, not sure what to do here come May 1st.

**Comment by yashaRO** [comment]
Not even, will be trying to build my own alt config prob mid-end March.

**Comment by ghost** [comment]
That's basically where I'm at. Hopefully I can whip up a Dockerfile to handle this and just use the Heroku "container" stack.

**Comment by damaneice** [comment]
Here is my Dockerfile:

```
FROM node:9

RUN apt-get update &&\
    apt-get install -y libgtk2.0-0 libgconf-2-4 \
    libnotify4 libasound2 libxtst6 libxss1 libnss3 xvfb
RUN npm install -g yarn

RUN mkdir /app
WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY . .
RUN chmod +x /usr/local/bin/yarn
RUN yarn install
```

It is an old version of node. You can probably try and get this working with a newer node version.

**Comment by ghost** [comment]
I'll give this a try! Thanks @damaneice

**Comment by yashaRO** [comment]
@sgowen Have you tried it yet?

**Comment by ghost** [comment]
@yashaRO not yet, as the project I am on is currently suspended amidst the COVID outbreak. Assuming it picks back up in the next few weeks, I'll give a try before the Cedar-14 EOL on May 1st

**Comment by ghost** [comment]
Yay, the Cedar-14 EOL date has been extended! https://hello.heroku.com/webmail/36622/937816529/40854764157caf031003b1c12134fd67c5ae482245bc1bb39dd2f553109833a1

**Comment by yashaRO** [comment]
What's funny is they say
> At Salesforce, our top priority is providing you a trusted platform. As we all face the COVID-19 (coronavirus) pandemic, we are postponing the close of the Cedar-14 EOL window to November 2nd, 2020...

**Salesforce**

**Comment by ghost** [comment]
@yashaRO haha

**Comment by ghost** [comment]
@yashaRO ended up switching to puppeteer following the instructions here: https://github.com/puppeteer/puppeteer/issues/758

I'm on heroku-16 now

**Comment by yashaRO** [comment]
Oh nice, were there any tradeoffs or does your project work the same?

**Comment by ghost** [comment]
Works exactly the same, except I was able to delete my Aptfile and .profile files!
