### ISSUE TITLE
Unable to clone repo despite public ssh 

### ISSUE THREAD

**Issue by robertlangereis** [oscarmorrison/nightmare-heroku#14]
I'm not all that familiar with the workings of (public) ssh keys, but despite having a working public ssh (id_rsa), I'm unable to clone your repo. It results in the the error:  
_git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository._

**Comment by leviwheatcroft** [comment]
This is most likely an issue with your ssh / git configuration rather than an issue with this repo.

The help docs [are pretty good](https://help.github.com/en/github/authenticating-to-github/testing-your-ssh-connection)

**Comment by robertlangereis** [comment]
Awesome, thanks for the support.
