### ISSUE TITLE
Pairing with a web server?

### ISSUE THREAD

**Issue by youmustfight** [oscarmorrison/nightmare-heroku#4]
This has been very helpful, thank you! I have a web server that when pinged, runs nightmarejs and saves some results. I just realized nightmare is running from my node/express server. Do you have any suggestions for passing off work from the web server to the worker?

EDIT: Ah, think this is getting at my need: https://devcenter.heroku.com/articles/asynchronous-web-worker-model-using-rabbitmq-in-node -- perhaps would be cool to incorporate something similar to your repo!

**Comment by killa-kyle** [comment]
@youmustfight I've gotten nightmare running with an express server using [Kue](https://github.com/Automattic/kue), where visiting a URL creates a 'job' and hands it off to my 'worker.js' file to do the actual scrape.

**Comment by oscarmorrison** [comment]
Hey @youmustfight going to close this issue.

Essentially you just want something to handle jobs. Can use Kue as @killa-kyle suggested, [node-schedule](https://github.com/node-schedule/node-schedule) or as your edit suggests
https://devcenter.heroku.com/articles/asynchronous-web-worker-model-using-rabbitmq-in-node

Happy to incorporate some job handling if you want to open a PR? Cheers

**Comment by SagiMedina** [comment]
@killa-kyle Can you share an example please?
