### ISSUE TITLE
electron error: symbol lookup error, undefined symbol

### ISSUE THREAD

**Issue by seanpascoe** [oscarmorrison/nightmare-heroku#8]
Hey @oscarmorrison , first of all, thanks for putting the time into this. 
I've followed your directions with a couple different instances and I keep getting the same error:
```
  electron:stderr /app/node_modules/electron/dist/electron: symbol lookup error: /app/node_modules/electron/dist/electron: undefined symbol: _ZN12v8_inspector8protocol8Debugger3API6Paused10ReasonEnum3XHRE +96ms
  nightmare electron child process exited with code 127: command not found - you may not have electron installed correctly +8ms
```
Do you have any idea what this is about? Thanks again

**Comment by JonathanKolnik** [comment]
+1

**Comment by causztic** [comment]
I am able to get it working on heroku by updating the electron-install-buildpack's electron version to be the same as Nightmare.js's. I have made a pull request on their repo
https://github.com/benschwarz/heroku-electron-buildpack/pull/2

You can also give my fork a try and see whether it works for you.

**Comment by oscarmorrison** [comment]
Thanks @seanpascoe well try and get some time to look into this. 
Open to PR's aswell

**Comment by ronnakamoto** [comment]
@oscarmorrison This is what I get after deploying [https://github.com/oscarmorrison/nightmare-heroku](https://github.com/oscarmorrison/nightmare-heroku):

- nightmare queueing action "goto" for http://blog.oscarmorrison.com/nightmarejs-on-heroku-the-ultimate-scraping-setup/ +11ms
-   nightmare queueing action "wait" +1ms
-   nightmare queueing action "evaluate" +0ms
-   nightmare running +2ms
-   electron:stderr /app/node_modules/electron/dist/electron: symbol lookup error: /app/node_modules/electron/dist/electron: undefined symbol: _ZN12v8_inspector8protocol8Debugger3API6Paused10ReasonEnum3XHRE +161ms
-   nightmare electron child process exited with code 127: command not found - you may not have electron installed correctly +11ms
-   nightmare electron child process not started yet, skipping kill. 

This is displayed when I execute the code as `heroku run DEBUG=nightmare*,electron:* node --harmony index.js`.

Someone please help.

**Comment by causztic** [comment]
@ubuntugod did you try my buildpack instead as it has an updated electron version? https://github.com/causztic/heroku-electron-buildpack

I was able to run electron with nightmare with the updated version.

**Comment by ronnakamoto** [comment]
@causztic Yes, I forked from your commit to [https://github.com/ubuntugod/heroku-electron-buildpack](https://github.com/ubuntugod/heroku-electron-buildpack ).

I am new to heroku(been playing with it for about 1 day). I added the above buildpack to the `.buildpacks` file such that its content is:

- https://github.com/heroku/heroku-buildpack-apt
- https://github.com/captain401/heroku-buildpack-xvfb.git
- https://github.com/ubuntugod/heroku-electron-buildpack.git
- https://github.com/heroku/heroku-buildpack-nodejs.git

Then I deployed it to heroku. During the depolyment I could see these in the console:

- remote: -----> Electron app detected
- remote: -----> Extracting Electron 1.8.4 binaries to /tmp/build_ef2080b7a4a37719b8d0869bd9ba943e/vendor/electron

I assume this makes sure that the latest version of electron will be available later.

But there was something that didn't feel right to me. I had that feeling when I saw these lines in the console before the above lines:

- remote: -----> Xvfb-setup app detected
- remote: -----> Electron app detected
- remote: -----> Extracting Electron 0.37.6 binaries to /tmp/build_ef2080b7a4a37719b8d0869bd9ba943e/vendor/electron
- remote: -----> Moving Electron to /tmp/build_ef2080b7a4a37719b8d0869bd9ba943e/vendor/electron

I am not sure why the 0.37.6 binaries are being extracted even when I applied the latest buildpack for electron from your repo.

I still get this error:
`electron:stderr /app/node_modules/electron/dist/electron: symbol lookup error: /app/node_modules/electron/dist/electron: undefined symbol: _ZN12v8_inspector8protocol8Debugger3API6Paused10ReasonEnum3XHRE +161ms`
I am not sure what I am doing wrong. I am using the `Cedar-14` stack on heroku.

**UPDATE**
I just checked the buildpacks currently applied to heroku by running `heroku buildpacks` and I saw that the BUILPACK URL that had the old electron version was also there. So, I removed it. Then, deployed the app again and now it works like a charm.

Thanks @causztic for the electron buildpack.

**Comment by causztic** [comment]
glad it worked out for you!

**Comment by seanpascoe** [comment]
thanks @causztic, your buildpack works great!

**Comment by damaneice** [comment]
Has anyone gotten this to work using the Heroku-16 stack?

**Comment by nottnt** [comment]
i have a poblem **nightmare electron child process exited with code 127: command not found - you may not have electron installed correctly** and **electron:stderr /app/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory** on Heroku-16 stack 
my 
npm :5.7.1 
node :8.9.4
eletron:1.8.4
nightmare:3.0.1
in .buildpacks
has 
https://github.com/heroku/heroku-buildpack-apt
https://github.com/captain401/heroku-buildpack-xvfb.git
https://github.com/causztic/heroku-electron-buildpack
https://github.com/heroku/heroku-buildpack-nodejs.git

**UPDATE** I roll back version heroku from stack-16 to cedar-14  It work great!!!
